export const RESISTOR_HEIGHT = 250;
export const RESISTOR_WIDTH = 450;
export const SPASE_BETWEEN_COLORED_SQUARE_Y_AXIOS = 3;
export const SPASE_BETWEEN_COLORED_SQUARE_X_AXIOS = 4;
export const COUNT_COLORED_SQUARE_X_AXIOS = 6;