export const RESISTOR_HEIGHT = 250;
export const RESISTOR_WIDTH = 450;
export const SPASE_BETWEEN_COLORED_RECTANGLE_Y_AXIOS = 3;
export const SPASE_BETWEEN_COLORED_RECTANGLE_X_AXIOS = 4;
export const RECTANGLE_HEIGHT = 40;
export const HEIGHT_SHRINK_COEFFICIENT = 0.2;
export const ROTATION_COEFFICIENT = 0.1;