export const RESISTOR_HEIGHT = 300;
export const RESISTOR_WIDTH = 450;
export const SPASE_BETWEEN_COLORED_SQUARE_Y_AXIOS = 2;
export const SPASE_BETWEEN_COLORED_SQUARE_X_AXIOS = 5;
export const COUNT_COLORED_SQUARE_X_AXIOS = 6;